#!/usr/bin/env bash
# Publish the demo pages to the `www` branch, for GitHub Pages: the contents of
# demo/ hoisted to the branch root, an index.html listing the pages, and
# .nojekyll. Copies only what git tracks on the current commit — never the
# working tree, which may hold ignored files (last year's pen carries a key).
#
#   bash scripts/publish-www.sh          # rebuild www from HEAD and push it
#   bash scripts/publish-www.sh --no-push
#
# Pages settings: deploy from branch `www`, folder `/ (root)`. Run this after
# every merge that touches demo/; the commit message records the source sha.
set -euo pipefail
root="$(git rev-parse --show-toplevel)"
src="$(git -C "$root" rev-parse --short HEAD)"
tmp="$(mktemp -d)"; trap 'git -C "$root" worktree remove --force "$tmp" 2>/dev/null || rm -rf "$tmp"' EXIT

if git -C "$root" show-ref --quiet refs/heads/www || git -C "$root" ls-remote --exit-code --heads origin www >/dev/null 2>&1; then
  git -C "$root" fetch -q origin www 2>/dev/null || true
  git -C "$root" worktree add -q "$tmp" www 2>/dev/null || git -C "$root" worktree add -q -b www "$tmp" origin/www
  git -C "$tmp" rm -rq . 2>/dev/null || true
else
  git -C "$root" worktree add -q --detach "$tmp"
  git -C "$tmp" switch -q --orphan www
  git -C "$tmp" rm -rqf . 2>/dev/null || true
fi
find "$tmp" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +

# tracked files under demo/, hoisted one level
git -C "$root" archive HEAD demo | tar -x -C "$tmp" --strip-components=1
touch "$tmp/.nojekyll"

# index.html: one entry per page, title and hint read from the page itself
python3 - "$tmp" "$src" <<'PY'
import html, pathlib, re, sys
root, src = pathlib.Path(sys.argv[1]), sys.argv[2]
pages = []
for idx in sorted(root.glob("*/index.html")):
    t = idx.read_text(errors="replace")
    title = re.search(r"<title>(.*?)</title>", t, re.S)
    hint = re.search(r'<p class="hint">(.*?)</p>', t, re.S)
    pages.append((idx.parent.name, html.unescape(title.group(1).strip()) if title else idx.parent.name,
                  re.sub(r"<[^>]+>", "", html.unescape(hint.group(1))).strip() if hint else ""))
others = [d.name for d in sorted(root.iterdir()) if d.is_dir() and d.name != ".git" and not (d / "index.html").exists()]
items = "\n".join(
    f'      <li><a href="{n}/"><b>{html.escape(ti)}</b></a>' + (f'<br><small>{html.escape(h)}</small>' if h else "") + "</li>"
    for n, ti, h in pages)
extra = "\n".join(f'      <li><a href="{n}/">{n}/</a> <small>files, no page</small></li>' for n in others)
(root / "index.html").write_text(f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>equinor/skills — demos</title>
<style>
  @font-face {{ font-family: Inter; src: url(https://cdn.eds.equinor.com/font/InterVariable.woff2) format("woff2-variations"); font-weight: 100 900; font-display: swap; }}
  html {{ background: oklch(0.97 0 0); color: oklch(0.23 0 0); }}
  body {{ margin: 0; font-family: Inter, system-ui, sans-serif; font-size: 1rem; line-height: 1.5; }}
  main {{ max-width: 44rem; margin: 0 auto; padding: 2.5rem 2rem; }}
  h1 {{ font-size: 1.75rem; line-height: 2.25rem; font-weight: 500; margin: 0 0 0.5rem; }}
  p, li {{ color: oklch(0.35 0 0); }}
  ul {{ padding: 0; list-style: none; display: grid; gap: 1rem; margin: 1.5rem 0; }}
  li {{ padding: 1rem 1.25rem; background: oklch(0.999 0 0); border-radius: 4px; box-shadow: inset 0 0 0 1px oklch(0.87 0 0); }}
  a {{ color: oklch(0.5 0.075 204.6); }} a b {{ font-weight: 500; }}
  small {{ color: oklch(0.46 0 0); }}
  footer {{ margin-top: 2rem; font-size: 0.875rem; color: oklch(0.46 0 0); }}
</style>
</head>
<body>
<main>
  <h1>Demos from equinor/skills</h1>
  <p>Pages shown at Into Design Systems Oslo, 9 September 2026. Each folder in the
     repository's <code>demo/</code> carries an <code>INTENT.md</code> that records why it is
     built the way it is.</p>
  <ul>
{items}
{extra}
  </ul>
  <footer>Skills: <a href="https://github.com/equinor/skills">github.com/equinor/skills</a> ·
    <code>npx skills add equinor/skills --skill &lt;name&gt;</code> · built from <code>{src}</code></footer>
</main>
</body>
</html>
''')
print(f"index.html: {len(pages)} pages, {len(others)} folders")
PY

git -C "$tmp" add -A
if git -C "$tmp" diff --cached --quiet; then echo "www is already up to date with $src"; exit 0; fi
git -C "$tmp" -c core.hooksPath=/dev/null commit -q -m "Publish demo/ from $src

Generated by scripts/publish-www.sh; do not edit here — change demo/ on main and re-run."
if [ "${1:-}" != "--no-push" ]; then git -C "$tmp" push -q -u origin www; fi
echo "www ← demo/ @ $src$( [ "${1:-}" = "--no-push" ] && echo ' (not pushed)')"
